In [2]:
import torch

In [3]:
x = torch.tensor([[3, 4.], [1., -1.]])
print(x)

tensor([[ 3.,  4.],
        [ 1., -1.]])


In [4]:
 torch.cuda.is_available()

True

In [5]:
x = torch.randn(3, requires_grad = True)
print(x)

tensor([-0.1041,  1.6308,  0.2740], requires_grad=True)


In [6]:
y = x * 2

In [7]:
print(y)

tensor([-0.2082,  3.2616,  0.5480], grad_fn=<MulBackward0>)


In [8]:
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-106.5872, 1669.9305,  280.5777], grad_fn=<MulBackward0>)


In [9]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)

In [10]:
print(v)

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])


In [11]:
y.backward(v)

In [12]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [15]:
print(y.grad_fn)

In [16]:
x1 = torch.randn(4, requires_grad = True)
print(x1)

tensor([-0.5870, -2.1714,  2.2047,  0.6812], requires_grad=True)


In [19]:
print(x1.grad)

None


In [20]:
y1 = x1 * 8
print(y1)

tensor([ -4.6960, -17.3713,  17.6374,   5.4499], grad_fn=<MulBackward0>)


In [22]:
v = torch.tensor([0.1, 1.0, 0.0001, 2], dtype=torch.float)
y1.backward(v)

In [23]:
print(x1.grad)

tensor([8.0000e-01, 8.0000e+00, 8.0000e-04, 1.6000e+01])


In [27]:
x2 = torch.randn(2, requires_grad = True)
y2 = x2 * 6
print(y2)

tensor([-3.7391,  1.3746], grad_fn=<MulBackward0>)


In [28]:
print(x2.grad)

None


In [29]:
x3 = torch.randn(3, requires_grad = True)

In [30]:
v1 = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
x3.backward(v1)

In [31]:
print(x3.grad)

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])


In [32]:
x4 = torch.randn(10)   #is in 1d
print(x4)

tensor([-2.0898,  2.8247, -0.1579, -0.7142, -0.1746, -1.1057, -0.0641,  0.0625,
         0.1353,  0.2178])


In [38]:
x4 = x4.view(1,-1)       #convert it into 2d
print(x4)

tensor([[-2.0898,  2.8247, -0.1579, -0.7142, -0.1746, -1.1057, -0.0641,  0.0625,
          0.1353,  0.2178]])


In [39]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [41]:
params = list(net.parameters())
print(params[0].size())  #conv1

torch.Size([6, 1, 5, 5])


In [43]:
print(params[2].size()) #conv2

torch.Size([16, 6, 5, 5])


In [44]:
input = torch.randn(1, 1, 32, 32)
print(input)


tensor([[[[-0.8016, -1.0495, -1.3647,  ..., -1.3378, -1.7943,  1.7691],
          [ 1.3831, -0.5700,  0.4234,  ...,  0.4424, -0.2398,  1.1352],
          [ 1.2076, -0.4084,  0.4920,  ...,  0.6379, -0.4449,  1.5037],
          ...,
          [ 0.2736,  1.5672,  0.9578,  ...,  0.3894, -1.2215, -0.0746],
          [ 0.7927,  0.1877,  1.2353,  ...,  0.2860,  1.5360, -0.3290],
          [-1.5754, -0.5739,  0.9772,  ..., -1.0737,  0.3619,  0.1066]]]])


In [55]:
x5 = torch.randn(32,32)

In [56]:
print(x5)

tensor([[-0.7057, -0.1300, -0.9469,  ...,  0.0057, -0.8545,  0.6184],
        [-1.0812,  0.1628, -2.1747,  ..., -2.0708,  1.0688, -0.2467],
        [-2.1951,  0.8914, -1.1053,  ...,  0.8640, -0.1642,  1.0784],
        ...,
        [ 0.4822, -1.3096,  0.6993,  ..., -0.3814, -0.8518,  0.0403],
        [-0.0676, -0.1144,  0.5220,  ...,  0.4302, -0.0896, -0.7892],
        [ 0.8556, -0.1478,  0.2771,  ..., -1.7069,  0.2707, -1.0108]])


In [57]:
out = net(input)
print(out)

tensor([[-0.2846,  0.0044,  0.0076, -0.0764,  0.1481,  0.1651,  0.0142, -0.0640,
         -0.0739,  0.0227]], grad_fn=<AddmmBackward>)


In [58]:
net.zero_grad()    #zeros the buffer grad
out.backward(torch.randn(1, 10))   

In [60]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.4348, grad_fn=<MseLossBackward>)


In [61]:
print(loss.grad_fn)

In [62]:
print(loss.backward())

None


In [64]:
net.zero_grad()  

In [68]:
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()



conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])


RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [71]:
output = net(input)
target1 = torch.randn(10)  # a dummy target, for example
target1 = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss1 = criterion(output, target1)
print(loss1)

tensor(0.4348, grad_fn=<MseLossBackward>)


In [72]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss1.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0130,  0.0037, -0.0074, -0.0003, -0.0023, -0.0006])


In [74]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.02)

In [75]:
optimizer.step()

In [83]:
g = torch.randn(1, requires_grad = True)
print(g)

tensor([1.3362], requires_grad=True)


In [84]:
g.backward()

In [85]:
print(g.grad)

tensor([1.])


In [86]:
g1 = torch.randn(2, requires_grad = True)
print(g1)

tensor([2.0522, 1.4451], requires_grad=True)


In [87]:
g1.backward(torch.randn(2))

In [88]:
print(g1.grad)

tensor([ 1.0379, -0.9024])


In [89]:
print(loss1.grad)

None


In [98]:
g2 = torch.randn(1,requires_grad = True)
print(g2)

tensor([-0.7628], requires_grad=True)


In [100]:
g2.backward()

In [101]:
print(g2.grad)

tensor([2.])
