In [1]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from PIL import Image
import torchvision
import matplotlib.pyplot as plt
import numpy as np
import torch
import os
import time
import random
%matplotlib inline

In [12]:
from __future__ import print_function, division

import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.optim import lr_scheduler
from torchvision import datasets, models, transforms

In [13]:
train_Aug = torchvision.transforms.Compose([torchvision.transforms.Resize((224, 224)),    
                                            torchvision.transforms.RandomRotation((-20, 20)),  
                                            torchvision.transforms.RandomAffine(0, translate=None, scale=[0.7, 1.3], shear=None, resample=False, fillcolor=0), 
                                            torchvision.transforms.ToTensor()])
test_Aug = torchvision.transforms.Compose([torchvision.transforms.Resize((224, 224)),  
                                           torchvision.transforms.ToTensor()])

In [14]:
base_dir = "C:\\Users\\91958\\elocations_dataset"
os.listdir(base_dir)

['test', 'train']

In [15]:
train_dir = "C:\\Users\\91958\\elocations_dataset\\train"
os.listdir(train_dir)

['bad', 'good']

In [16]:
trainset = torchvision.datasets.ImageFolder(train_dir,transform = train_Aug)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=30, shuffle=True, num_workers=2)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [17]:
class_names = trainset.classes
len(class_names)

2

In [18]:
my_resnet_model = models.resnet34(pretrained=True)

num_features = my_resnet_model.fc.in_features
my_resnet_model.fc = nn.Linear(num_features, 2)

In [19]:
my_resnet_model = my_resnet_model.to(device)
criterion = nn.CrossEntropyLoss()

# Observe that all parameters are being optimized
optimizer_ft = optim.SGD(my_resnet_model.parameters(), lr=0.001, momentum=0.9)

# Decay LR by a factor of 0.1 every 7 epochs
exp_lr_scheduler = lr_scheduler.StepLR(optimizer_ft, step_size=7, gamma=0.1)

In [21]:
model_dir = 'C:\\Users\\91958\\'
num_epochs = 10
for epoch in range(num_epochs):
    correct = 0
    total = 0
    for i, data in enumerate(trainloader, 0): 
        exp_lr_scheduler.step()
        my_resnet_model.train()  # Set model to training mode
        
        for inputs, labels in trainloader:
                inputs = inputs.to(device) 
                labels = labels.to(device)
                
                optimizer_ft.zero_grad()
                outputs = my_resnet_model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer_ft.step()
                
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        # correct += (outputs == labels).float().sum()
        print("Epoch {}/{}, Loss: {:.3f}, Accuracy: {:.3f}".format(epoch+1,num_epochs, loss.item(), correct/total))
        
        torch.save(my_resnet_model.state_dict(), os.path.join(model_dir, 'epoch-{}.pt'.format(epoch)))

print('Finished Training')

Epoch 1/10, Loss: 0.012, Accuracy: 0.981
Epoch 1/10, Loss: 3.447, Accuracy: 0.977
Epoch 1/10, Loss: 0.144, Accuracy: 0.978
Epoch 1/10, Loss: 0.101, Accuracy: 0.979
Epoch 1/10, Loss: 0.118, Accuracy: 0.980
Epoch 1/10, Loss: 0.071, Accuracy: 0.980
Epoch 1/10, Loss: 0.590, Accuracy: 0.980
Epoch 1/10, Loss: 0.527, Accuracy: 0.980
Epoch 1/10, Loss: 0.012, Accuracy: 0.980
Epoch 1/10, Loss: 0.005, Accuracy: 0.980
Epoch 1/10, Loss: 0.010, Accuracy: 0.980
Epoch 1/10, Loss: 0.059, Accuracy: 0.980
Epoch 1/10, Loss: 0.192, Accuracy: 0.979
Epoch 1/10, Loss: 0.442, Accuracy: 0.979
Epoch 1/10, Loss: 0.004, Accuracy: 0.979
Epoch 1/10, Loss: 0.080, Accuracy: 0.979
Epoch 1/10, Loss: 0.059, Accuracy: 0.979
Epoch 1/10, Loss: 0.387, Accuracy: 0.979
Epoch 1/10, Loss: 0.007, Accuracy: 0.979
Epoch 1/10, Loss: 0.002, Accuracy: 0.979
Epoch 1/10, Loss: 0.026, Accuracy: 0.979
Epoch 1/10, Loss: 0.011, Accuracy: 0.979
Epoch 1/10, Loss: 0.441, Accuracy: 0.979
Epoch 1/10, Loss: 1.215, Accuracy: 0.979
Epoch 1/10, Loss

Epoch 3/10, Loss: 0.003, Accuracy: 0.979
Epoch 3/10, Loss: 0.457, Accuracy: 0.979
Epoch 3/10, Loss: 0.062, Accuracy: 0.979
Epoch 3/10, Loss: 0.040, Accuracy: 0.979
Epoch 3/10, Loss: 0.065, Accuracy: 0.979
Epoch 3/10, Loss: 0.124, Accuracy: 0.979
Epoch 3/10, Loss: 0.369, Accuracy: 0.979
Epoch 3/10, Loss: 0.025, Accuracy: 0.979
Epoch 3/10, Loss: 0.029, Accuracy: 0.979
Epoch 3/10, Loss: 0.340, Accuracy: 0.979
Epoch 3/10, Loss: 0.272, Accuracy: 0.979
Epoch 3/10, Loss: 0.006, Accuracy: 0.979
Epoch 3/10, Loss: 0.009, Accuracy: 0.979
Epoch 3/10, Loss: 0.068, Accuracy: 0.979
Epoch 3/10, Loss: 0.024, Accuracy: 0.979
Epoch 3/10, Loss: 0.429, Accuracy: 0.979
Epoch 3/10, Loss: 0.004, Accuracy: 0.979
Epoch 3/10, Loss: 0.004, Accuracy: 0.979
Epoch 3/10, Loss: 0.742, Accuracy: 0.979
Epoch 3/10, Loss: 0.044, Accuracy: 0.979
Epoch 3/10, Loss: 0.096, Accuracy: 0.979
Epoch 3/10, Loss: 0.241, Accuracy: 0.979
Epoch 3/10, Loss: 0.004, Accuracy: 0.979
Epoch 3/10, Loss: 0.350, Accuracy: 0.979
Epoch 3/10, Loss

Epoch 6/10, Loss: 0.051, Accuracy: 0.980
Epoch 6/10, Loss: 0.001, Accuracy: 0.979
Epoch 6/10, Loss: 0.170, Accuracy: 0.979
Epoch 6/10, Loss: 0.257, Accuracy: 0.979
Epoch 6/10, Loss: 0.089, Accuracy: 0.979
Epoch 6/10, Loss: 0.003, Accuracy: 0.979
Epoch 6/10, Loss: 0.011, Accuracy: 0.979
Epoch 6/10, Loss: 0.029, Accuracy: 0.979
Epoch 6/10, Loss: 0.042, Accuracy: 0.979
Epoch 6/10, Loss: 0.001, Accuracy: 0.979
Epoch 6/10, Loss: 0.024, Accuracy: 0.979
Epoch 6/10, Loss: 0.467, Accuracy: 0.979
Epoch 6/10, Loss: 0.029, Accuracy: 0.979
Epoch 6/10, Loss: 0.058, Accuracy: 0.979
Epoch 6/10, Loss: 0.015, Accuracy: 0.979
Epoch 6/10, Loss: 0.414, Accuracy: 0.979
Epoch 6/10, Loss: 0.037, Accuracy: 0.979
Epoch 6/10, Loss: 1.647, Accuracy: 0.979
Epoch 6/10, Loss: 0.060, Accuracy: 0.979
Epoch 6/10, Loss: 0.107, Accuracy: 0.979
Epoch 6/10, Loss: 0.274, Accuracy: 0.979
Epoch 6/10, Loss: 0.120, Accuracy: 0.979
Epoch 6/10, Loss: 0.094, Accuracy: 0.979
Epoch 6/10, Loss: 0.842, Accuracy: 0.979
Epoch 6/10, Loss

Epoch 9/10, Loss: 0.148, Accuracy: 0.981
Epoch 9/10, Loss: 0.004, Accuracy: 0.977
Epoch 9/10, Loss: 0.009, Accuracy: 0.976
Epoch 9/10, Loss: 0.025, Accuracy: 0.978
Epoch 9/10, Loss: 0.037, Accuracy: 0.978
Epoch 9/10, Loss: 0.587, Accuracy: 0.979
Epoch 9/10, Loss: 0.189, Accuracy: 0.978
Epoch 9/10, Loss: 0.111, Accuracy: 0.977
Epoch 9/10, Loss: 0.111, Accuracy: 0.977
Epoch 9/10, Loss: 0.069, Accuracy: 0.977
Epoch 9/10, Loss: 0.089, Accuracy: 0.977
Epoch 9/10, Loss: 0.136, Accuracy: 0.978
Epoch 9/10, Loss: 0.016, Accuracy: 0.978
Epoch 9/10, Loss: 0.247, Accuracy: 0.978
Epoch 9/10, Loss: 0.294, Accuracy: 0.978
Epoch 9/10, Loss: 0.057, Accuracy: 0.978
Epoch 9/10, Loss: 0.213, Accuracy: 0.978
Epoch 9/10, Loss: 0.086, Accuracy: 0.978
Epoch 9/10, Loss: 0.037, Accuracy: 0.978
Epoch 9/10, Loss: 0.001, Accuracy: 0.978
Epoch 9/10, Loss: 1.262, Accuracy: 0.979
Epoch 9/10, Loss: 0.022, Accuracy: 0.979
Epoch 9/10, Loss: 0.022, Accuracy: 0.979
Epoch 9/10, Loss: 0.029, Accuracy: 0.979
Epoch 9/10, Loss

In [23]:
test_dir = "C:\\Users\\91958\\elocations_dataset\\test"
testset = torchvision.datasets.ImageFolder(train_dir,transform = test_Aug)

testloader = torch.utils.data.DataLoader(testset, batch_size=30, shuffle=True, num_workers=2)

In [24]:
dataiter = iter(testloader)
images, labels = dataiter.next()

In [26]:
model = torch.load('C:\\Users\\91958\\epoch-9.pt')

In [30]:
my_resnet_model.load_state_dict(torch.load('C:\\Users\\91958\\epoch-9.pt'))

<All keys matched successfully>

In [31]:
my_resnet_model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [32]:
num_epochs = 10
for epoch in range(num_epochs):
    correct = 0
    total = 0
    for i, data in enumerate(testloader, 0): 
        exp_lr_scheduler.step()
        my_resnet_model.eval() 
        
        for inputs, labels in testloader:
                inputs = inputs.to(device) 
                labels = labels.to(device)
                
                optimizer_ft.zero_grad()
                outputs = my_resnet_model(inputs)
                
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        # correct += (outputs == labels).float().sum()
        print("Epoch {}/{}, Accuracy: {:.3f}".format(epoch+1,num_epochs, correct/total))

print('Finished Testing')

Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy: 0.988
Epoch 1/10, Accuracy

KeyboardInterrupt: 

In [42]:
from PIL import Image
from torch.autograd import Variable

imsize = (224,224)
loader = transforms.Compose([transforms.Scale(imsize), transforms.ToTensor()])

def image_loader(image_name):
    """load image, returns cuda tensor"""
    image = Image.open(image_name)
    image = loader(image).float()
    image = Variable(image, requires_grad=True)
    image = image.unsqueeze(0)
    return image.cuda()

In [45]:
image = image_loader('C:\\Users\\91958\\food.jpeg')
# print(image)
output = my_resnet_model(image)

In [46]:
output

tensor([[ 4.4092, -5.7382]], device='cuda:0', grad_fn=<AddmmBackward>)

In [50]:
output.cpu().data.numpy().argmax()

0

In [51]:
value, index = torch.max(output,1)

In [52]:
value

tensor([4.4092], device='cuda:0', grad_fn=<MaxBackward0>)

In [53]:
index

tensor([0], device='cuda:0')

In [54]:
image1 = image_loader('C:\\Users\\91958\\good.jpeg')
output1 = my_resnet_model(image1)

In [55]:
output1.cpu().data.numpy().argmax()

1

In [56]:
image2 = image_loader('C:\\Users\\91958\\humans.jpeg')
output2 = my_resnet_model(image2)

In [57]:
output2.cpu().data.numpy().argmax()

0